name: Build & Release Chrome Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Get tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Zip extension
        run: |
          cd dist
          zip -r ../mochimo-chromium-${TAG_NAME}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mochimo-chromium-${{ env.TAG_NAME }}.zip
          body: |
            ## How to manually install the Chrome extension

            1. Download the `mochimo-chromium-${{ env.TAG_NAME }}.zip` file from this release.
            2. Extract its contents to a folder on your computer.
            3. Open Chrome and go to `chrome://extensions`.
            4. Enable Developer mode (top right corner).
            5. Click "Load unpacked" and select the extracted folder.

            ---

            This release was automatically generated by GitHub Actions.
            It contains the latest version of the MochiWallet Chrome extension.
            See the documentation or repository for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
